TIMEOUT 30
DEFAULT helm-auto
MENU TITLE Helm Alpine

LABEL helm-auto
      MENU LABEL Helm Alpine (firmware-selected module)
      LINUX /boot/Image
      INITRD /boot/initramfs-helm
      FDTOVERLAYS /boot/dtb/helm-p3768.dtbo
      APPEND ${cbootargs} root=LABEL=HELM_ROOT rw rootwait rootfstype=ext4 noatime modules=phy-tegra194-p2u,pcie-tegra194,nvme console=ttyTCU0,115200 console=tty0 firmware_class.path=/lib/firmware nvme.use_threaded_interrupts=1

LABEL helm-orin-nx-16gb
      MENU LABEL Helm Alpine - Orin NX 16GB (P3767-0000)
      LINUX /boot/Image
      INITRD /boot/initramfs-helm
      FDT /boot/dtb/helm-p3767-0000.dtb
      APPEND ${cbootargs} root=LABEL=HELM_ROOT rw rootwait rootfstype=ext4 noatime modules=phy-tegra194-p2u,pcie-tegra194,nvme console=ttyTCU0,115200 console=tty0 firmware_class.path=/lib/firmware nvme.use_threaded_interrupts=1

LABEL helm-orin-nx-8gb
      MENU LABEL Helm Alpine - Orin NX 8GB (P3767-0001)
      LINUX /boot/Image
      INITRD /boot/initramfs-helm
      FDT /boot/dtb/helm-p3767-0001.dtb
      APPEND ${cbootargs} root=LABEL=HELM_ROOT rw rootwait rootfstype=ext4 noatime modules=phy-tegra194-p2u,pcie-tegra194,nvme console=ttyTCU0,115200 console=tty0 firmware_class.path=/lib/firmware nvme.use_threaded_interrupts=1

LABEL helm-orin-nano-8gb
      MENU LABEL Helm Alpine - Orin Nano 8GB (P3767-0003)
      LINUX /boot/Image
      INITRD /boot/initramfs-helm
      FDT /boot/dtb/helm-p3767-0003.dtb
      APPEND ${cbootargs} root=LABEL=HELM_ROOT rw rootwait rootfstype=ext4 noatime modules=phy-tegra194-p2u,pcie-tegra194,nvme console=ttyTCU0,115200 console=tty0 firmware_class.path=/lib/firmware nvme.use_threaded_interrupts=1

LABEL helm-orin-nano-4gb
      MENU LABEL Helm Alpine - Orin Nano 4GB (P3767-0004)
      LINUX /boot/Image
      INITRD /boot/initramfs-helm
      FDT /boot/dtb/helm-p3767-0004.dtb
      APPEND ${cbootargs} root=LABEL=HELM_ROOT rw rootwait rootfstype=ext4 noatime modules=phy-tegra194-p2u,pcie-tegra194,nvme console=ttyTCU0,115200 console=tty0 firmware_class.path=/lib/firmware nvme.use_threaded_interrupts=1

LABEL helm-orin-nano-8gb-sd
      MENU LABEL Helm Alpine - Orin Nano 8GB dev-kit/SD (P3767-0005)
      LINUX /boot/Image
      INITRD /boot/initramfs-helm
      FDT /boot/dtb/helm-p3767-0005.dtb
      APPEND ${cbootargs} root=LABEL=HELM_ROOT rw rootwait rootfstype=ext4 noatime modules=phy-tegra194-p2u,pcie-tegra194,nvme console=ttyTCU0,115200 console=tty0 firmware_class.path=/lib/firmware nvme.use_threaded_interrupts=1
