profile_id=helm-orin-nano-8gb-r39.2
profile_board='P3767-0003 Orin Nano 8GB, Helm carrier'
profile_sku=0003
profile_usb_pid=0x7523
profile_kernel_dtb=helm-p3767-0003.dtb
profile_bpmp_fw=bpmp_t234-TE950M-A1_prod_sigheader.bin.encrypt
profile_bpmp_dtb=tegra234-bpmp-3767-0003-3509-a02_with_odm_sigheader.dtb.encrypt
profile_dce_rcm=display-t234-dce_with_kernel_tegra234-p3768-0000+p3767-0003-nv_sigheader.bin.encrypt
profile_dce_qspi=display-t234-dce_with_kernel_tegra234-p3768-0000+p3767-0003-nv_aligned_blob_w_bin_sigheader.bin.encrypt
